### ISSUE TITLE
Get rid of orphan gauge processes

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#1]
If Visual Studio is killed or crashes, the child `gauge` processes are orphaned. These need to be killed.

**Comment by sriv** [comment]
There is check to gracefully kill child processes from within the runner. Unfortunately, at least in windows there is no easy way [AFAIK] to register a child process to be killed when parent dies, unless there is an explicit "kill process tree" instead of "kill process". 

Suggestions welcome.

**Comment by navaneeth** [comment]
You do this the other way. When Gauge starts, it gets the parent's pid. And keep looking whether the pid is available. If not, it can exit itself. This can be controlled via a command line flag so that it is applicable only when required.

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge#166
