### ISSUE TITLE
On refactoring, the spec file content changes to the last saved version

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#109]
_From @sguptatw on May 5, 2016 11:54_
### Expected behavior

Refactoring should not revert my spec file changes
### Actual behavior

Reverts to the last saved version of the file + new refactoring is applied
### Steps to reproduce
1. Create a spec

```
dfsd
====
kusfdsf sdfsdfsdf
Scenario
--------
* sfdsf "ab" "sdfsdf"
* The word "gauge" has "4" vowels.
* sfdsf "sdf" "wer"
* Almost words have vowels "sdf"
```
1. Give the implementation

```
  [Step("The word <word> has <expectedCount> vowels.")]
        public void VerifyVowelsCountInWord(string word, int expectedCount)
        {
        }

        [Step("Almost words have vowels <wordsTable>")]
        public void VerifyVowelsCountInMultipleWords(Table wordsTable)
        {
        }

[Step("sfdsf <> <sdfsdf>")]
        public void SfdsfSfdwithSfda1(string sdf,string sdfsdf)
        {
            sdf.Should().NotBe("werwerwer");
        }
```
1. Now save the implementation and the spec file
2. Open the spec file

```
ctrl-x on the line
The word "gauge" has "4" vowels.

without saving
Refactor 'sfdsf "sdf" "wer"' to 'sfd "sdf" "wer"'
```
1. The file changes to an inconsistent state
   i.e
   Reverts to the last saved version of the file + new refactoring is applied
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-05-03

Plugins
-------
csharp (0.7.3.nightly-2016-05-03)
html-report (2.1.1.nightly-2016-05-03)
java (0.4.0)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

_Copied from original issue: getgauge/gauge-csharp#68_

**Comment by sriv** [comment]
I dont think this is valid here. If you are editing a file in Visual Studio, the file remains in the buffer of Visual Studio (in memory) unless you save it. Gauge-csharp reads and refactors the file only from the disk, which means the file is saved.

**Comment by sriv** [comment]
Proposal: save the file/project before invoking the refactoring action.

**Comment by sguptatw** [comment]
Given that re-sharper behaves as expected. i.e I do not have to save the file to refactor this proposal is not a suitable solution.

**Comment by sriv** [comment]
> Does the proposal mean Gauge would save before refactoring?

Yes, to be specific, Gauge-VisualStudio plugin should save the changes before attempting to refactor.

**Comment by sguptatw** [comment]
unable to refactor to a new name

**Comment by sriv** [comment]
Seems to work with Gauge-VisualStudio 0.2.4. @sguptatw - please check and post back errors/stacktrace if there is an issue with refactoing.
