### ISSUE TITLE
Getting 'Failed to load Gauge api' on refactoring

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#111]
_From @sguptatw on May 4, 2016 13:11_

**Expected Behavior**
Refactoring should work seamlessly

**Actual Behavior**
Getting 'Failed to load Gauge api' on refactoring

**Steps to reproduce**

```
mkdir usingTemplate
cd usingTemplate
gauge --init csharp
```
1. execute specs

```
gauge specs
```
1. Open the project in Visual Studio
2. Try renaming the step without compiling
3. Get the error
4. This also occurs when the machine is put to sleep for sometime and I start working again

**Version**
VS 2015

```
Gauge version: 0.4.0

Plugins
-------
csharp (0.7.2)
html-report (2.1.0)
java (0.4.0)
ruby (0.2.0)
```

_Copied from original issue: getgauge/gauge-csharp#62_

**Comment by BugDiver** [comment]
I think it depends on #160.

**Comment by sriv** [comment]
@BugDiver - yes. Reason is that when running `gauge specs` the implementation is compiled in `Release` mode, thus the binaries are available in `bin\Release` folder. When the project is opened in Visual Studio, it opens in `Debug` mode, and cannot find the binaries.

Rebuild on project open will address this.
