### ISSUE TITLE
Mark Scenarios with missing Step implementations as "Inconclusive"

### ISSUE THREAD

**Issue by WonkiDonk** [getgauge/gauge-visualstudio#113]
This is a suggestion for improvement. I'm happy to pick up this ticket if you feel it's an issue that needs resolving in the C# runner rather than the core Gauge framework.

Currently, when you define a scenario with one or more unimplemented step definitions and you run the scenario, the scenario shows as passing.

I would like to suggest that, for clarity, when one or more of the step definitions have not yet been implemented (i.e.: there are no matching methods with `[StepAttibute]` bindings, Visual Studio Test Explorer reports the scenario as `Inconclusive`. At the moment, it shows such scenarios as `Passed`, even though they're not implemented.

**Comment by sriv** [comment]
Scenarios with unimplemented steps should be marked as `Failed`. It is a bug if it is marked as `Passed`. Could you share some way for us to replicate it?

On a related note, we have plans to revamp the specs execution via Visual Studio. Currently, it invokes `gauge` with relevant arguments, and looks at the `stdout`, and exit code to determine `pass`/`fail` and output.

getgauge/gauge#165 will allow us to have execution via `gauge`'s API, giving us more structured output from the run. 

If you notice the console run output (i.e. running `gauge specs` from command line), you will see that the scenarios with unimplemented steps are marked as `skipped`. We would like that to be consistent in Visual Studio as well.
