### ISSUE TITLE
Getting a security warning when adding a concept

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#115]
**Expected Behavior**
Should be able to add a file without a security warning

**Actual Behavior**
Getting a security exception

**Steps to reproduce**
1. In a visual studio gauge project, 

```
1. add a new item
2. Select the concept file type
```

Now I am getting the trust exception

<img width="569" alt="screen shot 2016-05-17 at 12 19 02 pm" src="https://cloud.githubusercontent.com/assets/6310197/15313621/0cc7464e-1c2a-11e6-8723-f788d1e02826.png">

**Versions**

```
Gauge version: 0.4.1.nightly-2016-05-13

Plugins
-------
csharp (0.7.3.nightly-2016-05-13)
html-report (2.1.1.nightly-2016-05-03)
java (0.4.0)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

**Comment by sriv** [comment]
Some research yielded these:

- http://stackoverflow.com/questions/34793599/how-to-make-the-visual-studio-2015-text-templating-security-warning-go-away

- https://social.msdn.microsoft.com/Forums/vstudio/en-US/aa247057-3d68-4cca-b6a8-3bea4fa34234/security-warning-dialog-for-custom-item-template?forum=vsx
