### ISSUE TITLE
With visual studio open with gauge project, install a gauge nightly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#116]
**Expected Behavior**
I should get a warning to close all relevant applications

**Actual Behavior**
I get an error

<img width="511" alt="screen shot 2016-05-17 at 1 28 28 pm" src="https://cloud.githubusercontent.com/assets/6310197/15315262/1bbe70f0-1c34-11e6-88d3-ebd61616ea47.png">

**Comment by sriv** [comment]
This issue was moved to getgauge/gauge#404
