### ISSUE TITLE
Test execution doesn't work with space in the directory path

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#119]
**Exepected Behavior**
Should be able to execute with space in the directory path

**Steps to reproduce**
1. Create a project in a path with space
2. Open the project in visual studio
3. run the specs
4. It does not run the specs

**Version**

```
VS - 0.2.1
Gauge version: 0.4.1.nightly-2016-05-16

Plugins
-------
csharp (0.7.3.nightly-2016-05-16)
html-report (2.1.0)
java (0.4.0)
js (1.2.0)
python (0.1.2)
ruby (0.2.0)
xml-report (0.1.2)

```

**Comment by sguptatw** [comment]
<img width="1391" alt="screen shot 2016-05-31 at 10 16 21 am" src="https://cloud.githubusercontent.com/assets/6310197/15663452/e60f74d2-2718-11e6-87d0-790748220b70.png">

**Comment by sriv** [comment]
Works on Gauge-Visualstudio v0.2.4.

Also works when `ExecutionAPI` is turned on.
