### ISSUE TITLE
Getting a null pointer exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#123]
**Expected behavior**
Should be able to add implementation to a step without getting an exception

**Actual behavior**
Getting an exception while adding an implementation to a class in a different assembly

**Step to reproduce**
1. Create a project `aaa`
2. Add a class library `bbb`.
3. Add a class c with using System only.
3. Add a spec to project `aaa`
4. Add two steps.
4. Now implement and give the implementation of step1 in c-> `bbb`.
5. Going back click on the step 2, which marks it as unimplemented. Now click on step1 , it also gets marked as unimplemented.
6. Give the implementation, and then the following exception occurs 

```
System.NullReferenceException: Object reference not set to an instance of an object. at Gauge.VisualStudio.Model.Project.GetStepImplementation(ITextSnapshotLine line) at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.<GetTags>d__0.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__5.MoveNext()
```

**Comment by BugDiver** [comment]
@sguptatw how are you giving the reference of class library ```bbb```  to project ```aaa```? As a project or as a ```dll```.

**Comment by sguptatw** [comment]
@BugDiver :This is by adding the project.
