### ISSUE TITLE
Test explorer does not refresh when a spec file is deleted

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#126]
**Expected Behavior**
The current specs/scenarios to be displayed or else the message to re-explore the tests to be displayed.

**Actual Behavior**
It remains unaffected when spec files are deleted

**Steps to reproduce**
1. An existing project with existing spec files with various scenarios
2. The test explorer shows all the scenarios.
3. Delete a spec file.
4. This scenario is still listed in the test runner.

**Version**
VS - 0.2.2

```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
csharp (0.7.3.nightly-2016-05-17)
html-report (2.1.1.nightly-2016-05-17)
java (0.4.0)
ruby (0.2.0)
```

**Comment by sriv** [comment]
Fix should be available in nightly > 20-dec-2016
