### ISSUE TITLE
should add using for required Namespaces while generating code

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#128]
**Expected Behavior**
should add using for required Namespaces while generating code

**Actual Behavior**
does not generate the namespace

**Steps tor reproduce**
1. Create a cs file `aaa`, with using System only.
2. Create a spec `bbb`, add a step
3. Give the implementation of the step in `aaa`
4. The code generation is successful and is reflected in `bbb`. However the code is not compiling as the required libs are not used in the cs file.

**Version**
VS - 0.2.2
```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
csharp (0.7.3.nightly-2016-05-17)
html-report (2.1.1.nightly-2016-05-17)
```

**Comment by sriv** [comment]
Available on Visual Studio nightly >= latest.nightly-2016-05-19

**Comment by sguptatw** [comment]
It is adding the namespace even if it is already existing.

**Comment by sriv** [comment]
Fixed check for existing using statements, Available on Visual Studio nightly >= latest.nightly-2016-05-24
