### ISSUE TITLE
Add support to debug a Gauge spec

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#13]
The current spec runner launches a new `gauge` process, passing spec to execute. 

Add provision to attach a debugger to the execution.

**Comment by FathimaHarris** [comment]
+1

**Comment by sriv** [comment]
In order to debug please ensure that you have the below installed:

- Gauge >= 0.1.4
- Gauge-CSharp >= 0.2.2
- Gauge Visual Studio >= 0.0.4
