### ISSUE TITLE
The project is incompatible with current version of Visual studio

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-visualstudio#132]
_From @itsmemittal on May 17, 2016 10:12_

Hi, 

I fork visual studio repository but when i am trying to load this project on VS 2013 or VS 2015 then giving me error "The project is incompatible with current version of Visual studio" for following project
I forked this repository because i want to contribute in it.
- Gauge.ItemTemplate.Concept

_Copied from original issue: getgauge/gauge#406_

**Comment by BugDiver** [comment]
_From @sriv on May 17, 2016 10:16_

Hi, you need to install the [Visual Studio SDK](https://msdn.microsoft.com/en-us/library/bb166441.aspx) to open the project. Please make sure that you have the VSSDK for the visual studio version that you plan to use. Currently the Gauge-VisualStudio project are developed on VS2013, so please could you stick to VS2013, we will upgrade the project at a later point.

thanks

**Comment by BugDiver** [comment]
@itsmemittal Is this issue resolved now?

**Comment by sriv** [comment]
Closing this. Please comment if the issue surfaces.
