### ISSUE TITLE
Unable to implement step from IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#139]
Getting an exception while trying to implement a method. 

**Steps to replicate**
- Initialized the project using Gauge Test project template.
- Upgrade the csharp lib version.
- Try implementing a step. Gives an exception.
- Re-open the project.
- The exception still persists.
- Unable to do any actions after that

**Version**

```
Gauge version: 0.6.2.nightly-2016-08-26

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-15)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
Cannot reproduce this in Gauge-VisualStudio 0.2.4. @sguptatw - please confirm this is an issue, and if you still see an exception in this action, please post a stacktrace.
