### ISSUE TITLE
The generated project from the template is giving lib version error

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#144]
_From @sguptatw on August 29, 2016 2:20_

**Expected Behavior**
The project initialization should be seamless taking care of the lib versions.

**Actual Behavior**
Using Gauge Web driver template and initialized the project. Getting the version incompatibility errors on running the specs.

_Copied from original issue: getgauge/gauge-csharp#93_

**Comment by sriv** [comment]
Please try updating the project's dependency (for `Gauge.CSharp.Lib`) via Nuget Package Manager. 

The minimum version of `Gauge.CSharp.Lib` for `Gauge.CSharp v0.9.1` is `0.6.0`.

**Comment by sguptatw** [comment]
@sriv Even though CSharp latest lib 0.6.1 is available and installed previously. On creating a new csharp project, it is using an older csharp version 0.5.~. Manually upgrading does solve the problem. However wanted to know if this is the expected behavior?

**Comment by sriv** [comment]
Unfortunately, nuget requires you to specify a version, and does not allow an option of "latest". So, while the templates can be kept upto date, it will only happen when Gauge-VisualStudio is released. 

Workaround: Use your project's Nuget Package Manager to keep dependencies upto date.
