### ISSUE TITLE
VS Exception - gauge TextSnapshotExtensions, something to do with UnimplementedStepTagger

### ISSUE THREAD

**Issue by bkim54** [getgauge/gauge-visualstudio#147]
I have added a gauge project to my solution and I get a VS Exception, looking at Microsoft\VIsualStudio\14.0\ActivityLog.xml this error message is repeated 4 times.

`System.InvalidOperationException: Sequence contains no matching element at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate) at Gauge.VisualStudio.Model.Extensions.TextSnapshotExtensions.GetProject(ITextSnapshot snapshot, DTE dte) at Gauge.VisualStudio.Highlighting.ImplementStepAction..ctor(SnapshotSpan span, UnimplementedStepTagger unimplementedStepTagger, IProject project) at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.GetSmartTagActions(SnapshotSpan span) at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.<GetTags>d__0.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__38.MoveNext()`

I cannot change a step/scenario's name and have the gauge update the tests.

I am using MS VS Studio Version 14 Update 3
Gauge Version 0.6.2
csharp plugin version 0.9.2
gauge VS plugin version 0.2.2

**Comment by ryanrosello** [comment]
This is happening for me too:
MS VS Studio 2015 Update 3
Gauge Version 0.6.2
csharp plugin version 0.9.2
Gauge.VisualStudio   1.0

**Comment by sriv** [comment]
One scenario where this can happen when opening a `spec` file that is outside the project.

Fixed via https://github.com/getgauge/gauge-visualstudio/commit/5b38172b50f97bf24b9dd87b2064852f7073af8a

**Comment by sguptatw** [comment]
Opening a spec that is outside the project no longer gives this exception.
Adding an existing Gauge project to another solution is not giving this exception.

**Comment by sriv** [comment]
@bkim54 @ryanrosello - if either of you have a use-case/scenario that can simulate this issue (other than the one mentioned above), please comment. Thanks.
