### ISSUE TITLE
Check for Gauge and Gauge C# installation

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#148]
Gauge Visual Studio plugin is useless without Gauge and Gauge-CSharp plugins installed.

On startup, if it's a gauge project, then ensure that Gauge / Gauge-CSharp is installed and the Gauge-VS plugin is compatible with the versions of Gauge and Gauge-CSharp.

**Comment by sriv** [comment]
Done via ae6f5d0abdedbb1469cbd1b9d0f0dde8d9e5a9e9, 6a95b50b15d7672a3344a55e1a13bfda3ed54f0d and ef791ce5dcf1438436ca558adeb1e6dc0997c41b

**Comment by sriv** [comment]
Fix should be available in nightly >=07/12/2016

**Comment by sguptatw** [comment]
Getting an exception while creating a project.

- Installed Gauge of 18-Oct
- Installed Gauge-csharp of 18-Oct
- Create a new project in VS
- Build the project
Getting a null pointer exception
```
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   --- End of inner exception stack trace ---
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject)
```

**Comment by sriv** [comment]
@sguptatw Unable to replicate. Which version of Gauge-VS are you using?

**Comment by apoorvam** [comment]
Tried with following versions of Gauge, C# plugin and VS plugin. It works fine. 

Gauge version: 0.6.3.nightly-2016-12-07
Plugins:
csharp (0.9.2)

It gives an error message saying `Gauge daemon is not started` if Gauge 0.6.2 is installed. This is correct because latest VS is not compatible with older version of Gauge.
