### ISSUE TITLE
[Refactor] Unable to refactor from the IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#152]
**Expected behaviour**
An user should be able to refactor a step any number of times.

**Actual behaviour**
The refactoring was successful once, but when the same step is refactored again, the action changes the step text and not the implementation.

**Steps to replicate**
* Create a new Gauge project with the basic template
* Refactor the vowel step more than once. You should see this error.
> This happens both with execution API on and off.

**Version**
```
gauge.visualstudio-latest.nightly-2016-12-06
Gauge version: 0.6.3.nightly-2016-12-07

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-12-06)
java (0.5.1)
ruby (0.3.1)
```

**Comment by sriv** [comment]
Fix should be available in nightly >= 07/12/2016
