### ISSUE TITLE
Should be able to run a project created from web driver template

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#153]
**Expected Behavior**
User should be able to run the project created using the web driver template.

**Actual behavior**
Getting compilation errors 'cause Gauge-csharp library is not available.
> This occurs for both execution API on and off

**Steps to replicate**
* Create a web project from template
* Run the project

**Version**
```
gauge.visualstudio-latest.nightly-2016-12-02
Gauge version: 0.6.3 - installed from the build pipeline few days ago

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-11-29)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
Fix should be available in nightly >=07/12/2016
