### ISSUE TITLE
Unable to continue working on an old project with latest VS nightly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#154]
**Expected Behavior**
I should be able to continue to work on an existing project.

**Actual Behavior**
I am unable to disable the use execution API flag by opening an existing Gauge project created with older VS

**Steps to replicate**
* Use an existing project created with an older VS.
* Open the project and try setting the flag of execution API.

**Version**
```
gauge.visualstudio-latest.nightly-2016-12-02
Gauge version: 0.6.3.nightly-2016-12-07

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-11-29)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
Unable to reproduce this. Please provide a sample project that can be used to simulate this issue.
