### ISSUE TITLE
Find usage should match for the given step only

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#155]
**Expected behaviour**
Find usage of a given step should match where this step is used in the test suite.

**Actual behavior**
It is matching a step with another step which starts with this step text but has more details to it.

**Steps to replicate**
* Create a step `Vowels in English language "aeiou".`
* Create another step `Vowels in English language "aeiou"def`
* Now find usages of the first step.
* It will find both steps

**Version**
```
Gauge version: 0.6.3.nightly-2016-12-07

Plugins
-------
csharp (0.9.3.nightly-2016-11-04)
html-report (2.2.0.nightly-2016-12-06)
java (0.5.1)
ruby (0.3.1)
```

**Comment by BugDiver** [comment]
Not able to replicate with the latest nightly.
