### ISSUE TITLE
The skipped scenarios are also marked as passed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#159]
**Expected behavior**
The skipped scenarios should be marked as grey(not green or red).

**Actual behavior**
The skipped scenarios is marked as green

**Steps to replicate**
* Create a spec with unimplemented step
* run the spec
* check the test explorer for the result. The scenario is marked in green rather than grey

**Version**
```
gauge.visualstudio-latest.nightly-2016-12-19

Gauge version: 0.7.1.nightly-2016-12-19

Plugins
-------
csharp (0.9.3.nightly-2016-12-09)
html-report (3.0.0.nightly-2016-12-13)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sriv** [comment]
When invoking `gauge` as a subprocess, the exit code is checked for failure/pass. Hence there is only a binary state available, thus making all non-failures as pass.

This should be addressed when using Gauge's ExecutionAPI, since it will yield more structured output.
