### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by maxtar** [getgauge/gauge-visualstudio#165]
### Expected behavior
I trying create specification in Russian language. When I select from context menu "Format file" I want to get pretty print file.

### Actual behavior
Russian chars encoded to unreadable symbols.

I have investigated this issue and noted that you save file in UTF-8 without BOM encoding, but VS expect utf-8 with BOM encoding. When I resave specification in external editor with BOM flag in VS will be OK.

And one more. After that I installed plugin Gauge.VisualStudio after every save it try to compile one. And VS works very slow due to it.

### Steps to reproduce
1. Create new specification file from Studio.
2. Write step in Russian.
3. In context menu select "Format file."

### Version Information

VisualStudio Version and Edition  :-
Gauge VisualStudio Plugin Version :-

```
Run gauge -v on your system and paste the results here.
```
gauge -v
Gauge version: 0.7.0

Plugins
-------
csharp (0.9.2)
html-report (3.0.1)
java (0.5.1)

**Comment by sriv** [comment]
@maxtar - thanks for bringing this up.

Will investigate the encoding issue.

> And one more. After that I installed plugin Gauge.VisualStudio after every save it try to compile one. And VS works very slow due to it.

Yes, this is also definitely something to address. I have raised this as a different issue [here](https://github.com/getgauge/gauge-visualstudio/issues/170).

**Comment by maxtar** [comment]
Thanx, will waiting. :)
