### ISSUE TITLE
Steps with implementation shown as unimplemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#166]
**Expected behavior**
Steps with implementation shown as implemented

**Actual behavior**
Steps with implementation shown as unimplemented

**Steps to replicate**
1. Create a new project.
2. Clean the project by deleting the output folders.
3. Close the project.
4. Re-open the project, all steps are shown as unimplemented
> Can we build the project on load?
5. Keep the spec file open.
6. Build the project.
7. The steps are still marked as unimplemented. The changes are reflected when the file is manually reloaded or when the user clicks on the step.

**Version**
```
Gauge version: 0.7.1.nightly-2016-12-20

Plugins
-------
csharp (0.9.3.nightly-2016-12-09)
html-report (3.0.1)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by sguptatw** [comment]
Building the project is the first action expected from the user to proceed to use Gauge. Can we build the project on load?

**Comment by kashishm** [comment]
Fix is available in nightly >= 2017-01-10

**Comment by sguptatw** [comment]
Opening an existing project is still giving steps as unimplemented.
