### ISSUE TITLE
Install from VSIX error: extension/package.json not found inside zip.

### ISSUE THREAD

**Issue by Noffica** [getgauge/gauge-visualstudio#171]
### Expected behaviour
The plugin installs.

### Actual behaviour
```
extension/package.json not found inside zip.
```

### Steps to reproduce
1. Navigate to https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.GaugepluginforVisualStudio
2. download the plugin
3. Launch VSC and install from VSIX the downloaded plugin

### Version Information

VisualStudio Version and Edition  :-
```
Visual Studio Code for Mac OS X
Version 1.8.1 (1.8.1)
```

Gauge VisualStudio Plugin Version :-
```
Gauge version: 0.7.0

Plugins
-------
html-report (3.0.1)
ruby (0.3.1)
```

### Notes:
The plugin is no longer available in the VSC Gallery.

**Comment by sriv** [comment]
The Gauge Visual Studio plugin is meant to be used with Visual Studio 2013/2015. It does not work with Visual Studio Code. 

We do not have support for VS Code presently.
