### ISSUE TITLE
VS2015 Enterprise unable to open plugin after installation

### ISSUE THREAD

**Issue by cynthisizer** [getgauge/gauge-visualstudio#176]
### Expected behavior
I should be able to use the plugin after I install in from "Extensions and Updates" within VS2015 32-bit Enterprise.  Running VS2015 as Administrator (my user account is an admin) on a Windows 10 64-bit virtual machine.

### Actual behavior
Plugin is unable to load:
![image](https://cloud.githubusercontent.com/assets/12108254/23478206/921fca5e-fe8e-11e6-96f6-9c25b90fcbba.png)

ActivityLog.xml snippet:
  <entry>
    <record>106</record>
    <time>2017/03/01 19:13:04.684</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Visual Studio Help Package]</description>
    <guid>{4A791146-19E4-11D3-B86B-00C04F79F802}</guid>
  </entry>
  <entry>
    <record>107</record>
    <time>2017/03/01 19:13:04.685</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{309AA1CD-4DC1-43E9-9D19-85B21ABF2520}</guid>
  </entry>
  <entry>
    <record>108</record>
    <time>2017/03/01 19:13:04.685</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [GaugePackage]</description>
    <guid>{309AA1CD-4DC1-43E9-9D19-85B21ABF2520}</guid>
  </entry>
  <entry>
    <record>109</record>
    <time>2017/03/01 19:13:04.711</time>
    <type>Information</type>
    <source>Package Framework</source>
    <description>Initialized ServiceProvider.GlobalProvider from SetSite.</description>
  </entry>
  <entry>
    <record>110</record>
    <time>2017/03/01 19:13:04.780</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [GaugePackage]Source: &apos;System&apos; Description: The system cannot find the file specified&#x000D;&#x000A;</description>
    <guid>{309AA1CD-4DC1-43E9-9D19-85B21ABF2520}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>111</record>
    <time>2017/03/01 19:13:04.798</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [GaugePackage](null)</description>
    <guid>{309AA1CD-4DC1-43E9-9D19-85B21ABF2520}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>112</record>
    <time>2017/03/01 19:13:04.800</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [GaugePackage]</description>
    <guid>{309AA1CD-4DC1-43E9-9D19-85B21ABF2520}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

### Steps to reproduce
1. Install Gauge.VisualStudio plugin through Updates and Extension
2. Restart VisualStudio as admin
3. Error message appears on restart

### Version Information

VisualStudio Version and Edition  :- VS2015 32-bit Enterprise
Gauge VisualStudio Plugin Version :- 0.2.3
Installed Gauge Version: 32-bit (C# was selected during installation)
```
Gauge version: 0.8.0

Plugins
-------
No plugins found
Plugins can be installed with `gauge --install {plugin-name}`
```

**Comment by cynthisizer** [comment]
I just noticed that the installer did not install any of the plugins I selected.  I just installed the csharp plugin.  I didn't get the error message on the restart (maybe that was my issue).  However, I don't see any visualization for the tool...

**Comment by cynthisizer** [comment]
This actually may be an issue with the Gauge installer.  I did select C# for the option (I actually selected all the language choices) and none of them seemed to be installed.  I didn't get an error at all during the installation.

**Comment by sriv** [comment]
Gauge plugins are installed at `USER` level, so if you install Gauge + plugins as a particular user, while `gauge` is available to other users, plugins are not.

I suspect you may have installed Gauge (and plugins selected in the installer) as a user, and when you run as Admin, these aren't available. 

Could you please run the installer and verify using `gauge -v` as the same user (admin or otherwise)? If this is still an issue, this will have to be fixed in [gauge](https://github.com/getgauge/gauge).
