### ISSUE TITLE
When rebuilding solution with compile errors the gauge Extension causes VS2015 to crash

### ISSUE THREAD

**Issue by davidjgaunt4** [getgauge/gauge-visualstudio#180]
### Expected behavior 
When rebuilding solution if errors are found then these are reported and VS2015 does not crash

### Actual behaviour
When rebuilding solution, if compile errors occur VS2015 appears to get stuck in a loop and eventually prompts with debug or close program prompt.
Disabling the VS studio extension for gauge prevents this issue from occurring
### Steps to reproduce
1. cause compile error in your gauge c# solution
2. from the VS menu bar select build=> rebuild solution
3. visual studio 2015 now gets stuck in a loop and eventually crashes.

### Version Information

VisualStudio Version and Edition  :- 2005 professional
Gauge VisualStudio Plugin Version :-0.3.0

```
Run gauge -v on your system and paste the results here.
```Gauge version: 0.8.0

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
xml-report (0.2.0)

**Comment by sriv** [comment]
@davidjgaunt4 - do you experience visual studio itself crashing or the gauge daemon?

**Comment by davidjgaunt4** [comment]
Hi visual studio crashes, it appears to get stuck building the project and eventually crashes.

**Comment by sguptatw** [comment]
Able to replicate the issue. 
In a Gauge project with Gauge-VS plugin installed there is a loop when there is a compilation error.

However this does not occur when it is non-Gauge project even with Gauge-VS plugin installed.
