### ISSUE TITLE
Getting the Windows Security Alert message on opening the VS

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#181]
<img width="542" alt="screen shot 2017-03-22 at 11 22 18 am" src="https://cloud.githubusercontent.com/assets/6310197/24184079/260e9fba-0ef2-11e7-9d0b-c3e42172c703.png">

**Version**
gauge.visualstudio-latest.nightly-2017-02-17
```
Gauge version: 0.8.2.nightly-2017-03-13

Plugins
-------
csharp (0.10.1.nightly-2017-02-17)
html-report (3.1.0)
java (0.6.2.nightly-2017-03-16)
```

**Comment by sriv** [comment]
Windows firewall works this way, it requires configuration to allow `gauge` to make connection to the internet.

Nothing to be done here, IMO. User has to approve the app's access, and gauge should (can) not attempt to bypass this.

If the user chooses, one can disable the windows firewall, or whitelist `gauge`. It is totally the user's choice.
