### ISSUE TITLE
Concept file does not have syntax highlighting

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#193]
**Expected behavior**
Concept file should have syntax highlighting.

**Actual behavior**
Concept file does not have syntax highlighting.

**Version**
```
Gauge version: 0.9.0.nightly-2017-06-29

Plugins
-------
csharp (0.10.2.nightly-2017-06-20)
html-report (4.0.1.nightly-2017-06-27)
```
VS - nightly-2017-06-21

**Comment by olcayekn** [comment]
I'm using VS 2015 Professional Version 14.0.25420.01 update 3 and im facing same issue. Even .spec files works well, .cpt files don't show highlights. Is there any fix for that issue?

**Comment by sriv** [comment]
can replicate this. My guess is that the `.cpt` extension is getting registered to a different extension. Need to look deeper.

**Comment by olcayekn** [comment]
Maybe it's caused by our connection. Our connection dont allow to download NuGet packages from virtual studio.
