### ISSUE TITLE
Unable to debug spec from visual studio 2015

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge-visualstudio#196]
When open gauge project in visual studio 2015 i am getting following error.

[Debug] Opening Gauge Daemon for Project : RegressionAutomation,  at ports: 1000, 2000
[Debug] Opening Gauge Daemon with PID: 17704
[Error] Failed to start Gauge Daemon: System.Exception: Could not connect ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:1000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   --- End of inner exception stack trace ---
   at Gauge.CSharp.Core.TcpClientWrapper..ctor(Int32 port)
   at Gauge.VisualStudio.Core.GaugeService.StartGaugeAsDaemon(Project gaugeProject)

**Comment by BugDiver** [comment]
@itsmemittal  Can you provide some more details about your issue?
* Gauge version
* Gauge-CSharp plugin version
* Gauge-VisualStudio Plugin version
* Any other info which you think can help us

**Comment by BugDiver** [comment]
@itsmemittal I see you had raised a similar issue [here](https://github.com/getgauge/gauge-csharp/issues/69#issuecomment-218946959) which got resolved. Are you still facing the issue?

**Comment by itsmemittal** [comment]
it is fixed after installing the correct version of gauge visual studio plugin.

**Comment by BugDiver** [comment]
@itsmemittal Thanks for your response. I'm closing the issue.
