### ISSUE TITLE
cant install gauge plugin for visual studio 2013 and 2015

### ISSUE THREAD

**Issue by mura28info** [getgauge/gauge-visualstudio#199]
### Expected behavior
Gauge projects Should be able to created and executed in Visual Studio using the Visual Studio plugin for Gauge. This plugin should be able to install from Visual Studio Gallery.

### Actual behavior
Could not find Gauge VS2013 extension under Tools>>> Extensions and Updates.Also tried with Gauge plugin for VisualStudio but while installing got the below error.

9/7/2017 3:33:55 PM - Microsoft VSIX Installer
9/7/2017 3:33:55 PM - -------------------------------------------
9/7/2017 3:33:56 PM - Initializing Install...
9/7/2017 3:33:56 PM - Extension Details...
9/7/2017 3:33:56 PM - 	Identifier      : Gauge.VS2013.ThoughtWorks.9731a722-d394-4c99-9df7-758867938fd6
9/7/2017 3:33:56 PM - 	Name            : Gauge plugin for VisualStudio
9/7/2017 3:33:56 PM - 	Author          : ThoughtWorks Inc.
9/7/2017 3:33:56 PM - 	Version         : 0.3.0
9/7/2017 3:33:56 PM - 	Description     : Visual Studio Extension for Gauge.
9/7/2017 3:33:56 PM - 	Locale          : en-US
9/7/2017 3:33:56 PM - 	MoreInfoURL     : http://getgauge.io/
9/7/2017 3:33:56 PM - 	InstalledByMSI  : False
9/7/2017 3:33:56 PM - 	SupportedFrameworkVersionRange : [4.5,4.6]
9/7/2017 3:33:56 PM - 
9/7/2017 3:33:56 PM - 	Supported Products : 
9/7/2017 3:33:56 PM - 		Microsoft.VisualStudio.Pro
9/7/2017 3:33:56 PM - 			Version : [12.0]
9/7/2017 3:33:56 PM - 		Microsoft.VisualStudio.Pro
9/7/2017 3:33:56 PM - 			Version : [14.0]
9/7/2017 3:33:56 PM - 
9/7/2017 3:33:56 PM - 	References      : 
9/7/2017 3:33:56 PM - 		-------------------------------------------------------
9/7/2017 3:33:56 PM - 		Identifier   : Microsoft.VisualStudio.MPF.12.0
9/7/2017 3:33:56 PM - 		Name         : Visual Studio MPF 12.0
9/7/2017 3:33:56 PM - 		Version      : [12.0,14.0]
9/7/2017 3:33:56 PM - 		MoreInfoURL  : 
9/7/2017 3:33:56 PM - 		Nested       : No
9/7/2017 3:33:56 PM - 
9/7/2017 3:33:56 PM - 
9/7/2017 3:33:56 PM - Searching for applicable products...
9/7/2017 3:33:56 PM - Found installed product - Microsoft Visual Studio Express 2013 for Windows Desktop
9/7/2017 3:33:56 PM - Found installed product - Microsoft Visual Studio Express 2015 for Windows Desktop
9/7/2017 3:33:56 PM - Found installed product - Global Location
9/7/2017 3:33:56 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Note : Same is the case with VS2015 as well.

### Steps to reproduce
1. Open Visual Studio Extension Manager from Tools -> Extensions and Updates.
2. Go to Visual Studio Gallery and search for Gauge VS2013.

### Version Information

VisualStudio Version and Edition  :- VS2013 Express and VS2015 Express
Gauge VisualStudio Plugin Version :-0.3.1

```
Run gauge -v on your system and paste the results here.
Gauge version: 0.9.1
Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
```

**Comment by mura28info** [comment]
I am able to see in professional version but not in express edition.

**Comment by Apoorva-GA** [comment]
@mura28info we don't have gauge-visualstudio support for visual studio express edition because Express edition [does not support extensions](https://visualstudiomagazine.com/articles/2014/05/21/no-extensions-for-visual-studio-express.aspx).

**Comment by sguptatw** [comment]
Closing this issue as there is no support for visual studio express.
