### ISSUE TITLE
Gauge Visual studio plugin executing scenario in alphabetically instead of scenario sequence.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#202]
_From @itsmemittal on September 8, 2017 13:7_

Gauge VisualStudio Plugin running spec scenario alphabetically.

### Expected behavior
When running specific spec from plugin then it should run spec in scenario order

### Actual behavior
running scenario alphabetically.

### Gauge version
```
Gauve - 0.9.1
Visual Studio Plugin version : 0.3 (Latest)
```

_Copied from original issue: getgauge/gauge#802_

**Comment by BugDiver** [comment]
This issue is still replicable.
