### ISSUE TITLE
Random issues with Visual Studio 2015 Plugin

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#204]
_From @itsmemittal on October 3, 2017 10:26_

Hi, 
I am facing random issues with visual studio plugin these following are coming randomly.

1. While Building project Test adapter saying "Object Reference Exception"
2. When Building project test adapter saying "The given key is not present in dictionary"
3. When i am changing anything in step implementation i am not able to debug i have to uninstall and re install plugin again.
4. Gauge Demon error.

Please guide me.

Thanks

_Copied from original issue: getgauge/gauge#829_

**Comment by sriv** [comment]
_From @itsmemittal on October 3, 2017 10:28_

![image](https://user-images.githubusercontent.com/3033471/31120884-af219226-a853-11e7-8215-0c91072a5db6.png)
Activity Log XML screenshot for errors.

**Comment by itsmemittal** [comment]
[ActivityLog.zip](https://github.com/getgauge/gauge-visualstudio/files/1352407/ActivityLog.zip)

**Comment by BugDiver** [comment]
Closing it since not enough info to replicate. Feel free reopen if still exist with latest `gauge` and `gauge Visual studio plugin`.
