### ISSUE TITLE
ImplementStep doesn't work in VS2015 Community

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge-visualstudio#205]
To recreate:
1. Create a new Gauge project.
2. Build the project (to trigger NuGet restore).
3. Open the StepImplementation.
4. Open the example.spec and use New Vertical Tab Group, so you can see both files.
5. Edit example.spec.
6.  Add the follow lines at the end:
```
Adding two numbers
------------------

This is the third scenario

* "1" plus "2" equals "3".
```
7. Save the file.  
8. Intellisense has appeared on the full stop.  Select it and click Implement Step.  After a second, Choose or Create a Class appears.  (IMO, if there's only one class, it should pre-select it.) Select StepImplementation.  Hit ENTER.  
9. Nothing happens.

The Output > Gauge window showed:
```
[Debug] Opening Gauge Daemon for Project : GaugeProject1,  at ports: 1000, 2000
[Debug] Opening Gauge Daemon with PID: 56304
[Debug] PID: 56304 ready, waiting for messages..
[Debug] Adding TestContainer: C:\Users\Public\Visual Studio\Investigations\GaugeProject1\GaugeProject1\specs\example.spec
[Debug] Adding TestContainer: C:\Users\Public\Visual Studio\Investigations\GaugeProject1\GaugeProject1\specs\example.spec
[Debug] Adding TestContainer: C:\Users\Public\Visual Studio\Investigations\GaugeProject1\GaugeProject1\specs\example.spec
```
### Version Information

VisualStudio Version and Edition  :- Visual Studio Community 2015 Update 3 v14.0.25431.01
Gauge VisualStudio Plugin Version :- 0.3.1.

```
 gauge -v
[DEPRECATED] This usage will be removed soon. Run `gauge help --legacy` for more info.
Gauge version: 0.9.3
Commit Hash: 724e6d3

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
```
[gauge.log](https://github.com/getgauge/gauge-visualstudio/files/1384491/gauge.log)
[api.log](https://github.com/getgauge/gauge-visualstudio/files/1384492/api.log)

**Comment by ssg47** [comment]
Is this supposed to have been fixed?  I've following my recreation steps from above and I'm still seeing the same behaviour.

I had a look through the commits and I couldn't see one between the 24 Oct 2017 and 3 Nov 2017 that seemed to be related to this issue.

I'm currently on:
Visual Studio Community 2015 Update 3 v14.0.25431.01
Gauge.VisualStudio 1.0 (according to Help > About Microsoft Visual Studio)
Gauge plugin for VisualStudio 0.3.7 (according to Tools > Extensions and Updates)
```
gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
html-report (4.0.5)
xml-report (0.2.0)  
```

**Comment by ssg47** [comment]
I'm in a different project, with two unimplemented steps in a spec file and the following just appeared:
![image](https://user-images.githubusercontent.com/15728152/56747803-88c62680-6776-11e9-9e82-96864739329c.png)

I checked in ActivityLog.xml and foun:

```  
  <entry>
    <record>577</record>
    <time>2019/04/25 15:20:13.624</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.&lt;GetTags&gt;d__4.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
  <entry>
    <record>578</record>
    <time>2019/04/25 15:20:13.625</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.&lt;GetTags&gt;d__4.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
  <entry>
    <record>579</record>
    <time>2019/04/25 15:20:13.626</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.&lt;GetTags&gt;d__4.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>
  </entry>
```

**Comment by sriv** [comment]
Thank you for the report @ssg47 - I am reopening this, we will get this sorted.

**Comment by ssg47** [comment]
This one must be frustrating for you: on the same machine that I had the problem 2 days ago, I started another project to recreate a different issue and the ImplementStep function worked.

**Comment by sriv** [comment]
"frustuating" describes it correctly :). On a serious note, I think there is definitely something we can handle better. 

From the stacktrace, I see that [`Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.GetTags`](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio/Highlighting/UnimplementedStepTagger.cs#L48) is the source of this error. I think its worth being a bit defensive here.
