### ISSUE TITLE
Multiple step implementations found. Gauge will skip execution of this scenario

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge-visualstudio#213]
### Expected behavior
I load my current solution.  The user.spec file is already open - this is the only spec file in the Gauge project.  All of the scenarios in the spec file are underscored with the wiggly red line.  When I highlight each one, I get:
    
    "Multiple step implementations found. Gauge will skip execution of this scenario"

There aren't multiple step implementations.  There are only three scenarios in one .spec file and there are only three implementation steps in the implementation class.  I don't think this error should exist.  This error didn't exist before I upgraded gauge and the vs plugin.

### Steps to reproduce
I haven't been able to reproduce this in a test project.  So far, it only happens in my current project.

### Version Information

VisualStudio Version and Edition  :- VS2015 Community Update 3 (14.0.25431.01)   (.NET v4.7.02053)
Gauge VisualStudio Plugin Version :- 0.3.3 - nightly-2017-10-30
```
Run gauge -v on your system and paste the results here.
```
Gauge version: 0.9.4
Commit Hash: c96bdbb

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by sguptatw** [comment]
@sriv : Can you please help with some steps to replicate the issue.

**Comment by sguptatw** [comment]
**Steps to replicate**
* create a new project from command line
* open the project in Visual studio.
* see the following error

<img width="960" alt="multiplestepimplementations" src="https://user-images.githubusercontent.com/6310197/32589304-d334b8fc-c539-11e7-9cda-7d01c2b53906.png">

**Version**
```
Gauge version: 0.9.5

Plugins
-------
csharp (0.10.2.nightly-2017-10-26)
html-report (4.0.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
gauge.visualstudio-latest.nightly-2017-11-03 
> Even though gauge.visualstudio-latest.nightly-2017-11-03 is installed in VS this appears as `gauge.visualstudio-latest.nightly-2017-11-02`

**Comment by sriv** [comment]
fix should be available in nightly >= 10/11/2017
