### ISSUE TITLE
Debugging scenarios doesn't hit breakpoints

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge-visualstudio#214]
Using the test project from [Issue 206](https://github.com/getgauge/gauge-visualstudio/issues/206), I place a breakpoint on the line 

    var rows = wordsTable.GetTableRows();

in 

    [Step("Almost all words have vowels <wordsTable>")]
    public void VerifyVowelsCountInMultipleWords(...

In TestExplorer, I right-click on `Vowel counts in multiple word` and select `Debug Selected Tests`.

### Expected behavior

Execution should pause on the specified line (`var rows = `).

### Actual behavior

Execution runs to completion.

### Steps to reproduce
See description above and [Issue 206](https://github.com/getgauge/gauge-visualstudio/issues/206)

### Version Information

VisualStudio Version and Edition  :-  VS2015 Community Update 3 (14.0.25431.01) (.NET v4.7.02053)
Gauge VisualStudio Plugin Version :- 0.3.3 - nightly-2017-10-30

```
Gauge version: 0.9.4
Commit Hash: c96bdbb

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by tzuravner** [comment]
also, happen to me.
building the project before debugging it did work for as a workaround
