### ISSUE TITLE
Project and Spec file templates don't appear in VS project templates

### ISSUE THREAD

**Issue by ovixeu** [getgauge/gauge-visualstudio#215]
### Expected behavior
Project and Spec file templates should be appear in VS project templates

### Actual behavior
Project and Spec file templates don't appear in VS project templates

### Steps to reproduce
1. Install extension from microsoft market place
2. Create new project
3. Select Gauge Test Project template

### Version Information

VisualStudio Version and Edition  :- 2015 Community and Enterprise
Gauge VisualStudio Plugin Version :- 0.3.2

Run gauge -v on your system and paste the results here.
```
U:\>gauge -v
Gauge version: 0.9.4
Commit Hash: c96bdbb

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
screenshot (0.0.1)
xml-report (0.2.0)

**Comment by sriv** [comment]
The project and item templates were removed from the plugin. The plan is to make them available as part of [Visual Studio Marketplace Templates](https://marketplace.visualstudio.com/search?target=VS&category=Templates&vsVersion=&subCategory=All&sortBy=Downloads).

This will help in maintaining templates without having to release the VS plugin.

Does this make sense? Or do you see a good reason to keep the templates within the plugin?

**Comment by opursail** [comment]
Maybe leave the project and item templates in the visual studio plugin until they are available as part of Visual Studio Marketplace Templates.

**Comment by sriv** [comment]
Thanks for the patience @ovixeu and @opursail .

I moved the templates to https://github.com/getgauge-contrib/gauge-visualstudio-templates

These are published here: https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.gauge-visualstudio-templates

It might take a while for the templates to appear in the search results of VS New Project window. If you can't locate it, do let me know.

Closing this issue, feel free to open any discussions in https://github.com/getgauge-contrib/gauge-visualstudio-templates

**Comment by nablik** [comment]
Hi @sriv, 
I am commenting here to avoid to open new ticket similar to this one. 
Actually, I am experiencing the same issue, 
`$ gauge --version
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
screenshot (0.0.1)`
Visual studio professional 2017 v15.9.11
I have installed the IDE plugin 0.3.7 and the latest nightly one(I mean I have tried both of them)
gauge is in the path, and there is GAUGE_HOME env-var. 
But I can't create a Guage project from VS2017. 
And even with a created project from the command line, the spec file could not be opened with Gauge 
![pb1](https://user-images.githubusercontent.com/11925279/56452651-9a00d480-632b-11e9-9a8a-7d4adbb72204.png)
![pb2](https://user-images.githubusercontent.com/11925279/56452654-a2f1a600-632b-11e9-9c00-76bbe9ac007d.png)
![pb3](https://user-images.githubusercontent.com/11925279/56452655-a4bb6980-632b-11e9-9538-10c7c91e9678.png)
![pb4](https://user-images.githubusercontent.com/11925279/56452656-a7b65a00-632b-11e9-9284-bf5354c634af.png)

**Comment by sriv** [comment]
Hi @nablik - so there are two parts of your comment:

1. unable to create a gauge project - You'll need to install https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.gauge-visualstudio-templates. But I see that it is available for VS 2015 only. Please log an issue for VS2017 support here: https://github.com/getgauge-contrib/gauge-visualstudio-templates

2. Unable to open a spec file - this is strange and not expected. Please create another issue in this repository, and if you have a sample project for us to check it, that'd be great. Also please mention which OS. VS version etc in the new issue.

I can say this isn't your fault and we'll help get this sorted.

**Comment by nablik** [comment]
Hi @sriv, I think there is no need to create an issue (https://github.com/getgauge/gauge-visualstudio/issues/251) I am importing dotnet project instead of csharp. I am a newbie in c# world, and I thought that the future of c# development is the core one. And I do like using VS2017 instead of VSCode. 
Is there by any chance a plan from Gauge to support dotnet (.NetCore) in the future or not ?

**Comment by sriv** [comment]
hi @nablik - We do not have a plan to add dotnet core support in visual studio (yet!), but I wouldn't rule it out. Honestly, we don't know how much of a value add it would be for our users. 

If this is something that is critical to a good number of users, we'd be happy to oblige. Please add your thoughts on #215. 

Pull requests are also most welcome, in case anyone is interested. 

/cc @zabil

**Comment by nablik** [comment]
will do. Thanks million.
