### ISSUE TITLE
After update can't use gauge

### ISSUE THREAD

**Issue by kstanowskifp** [getgauge/gauge-visualstudio#222]
### Expected behavior
After update plugin i expect that i can use gauge

### Actual behavior
Actual i can't use gauge. I have error message:
[Error] This plugin works with Gauge 0.9.6 or above. You have Gauge 0.9.5 installed. Please update your Gauge installation.
 Run 'gauge version' from your command prompt for installation information.

### Steps to reproduce
1. Update Gauge plugin for VS15 to 0.3.4 version
2. Restart VS15
3. Check Output error message

### Version Information

VisualStudio Version and Edition  :- 2015
Gauge VisualStudio Plugin Version :- 0.3.4

```
C:\Users\kstanowski>gauge -vv
Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
screenshot (0.0.1)

C:\Users\kstanowski>gauge -v
Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins
-------
csharp (0.10.1)
html-report (4.0.2)
screenshot (0.0.1)
```

**Comment by kashishm** [comment]
The latest Gauge VS plugin is only compatible with Gauge 0.9.6. We will be releasing Gauge soon. Till then please use VS plugin [0.3.3](https://github.com/getgauge/gauge-visualstudio/releases/tag/v0.3.3) or install Gauge using [nightly](https://bintray.com/gauge/Gauge/Nightly/_latestVersion).

**Comment by kstanowskifp** [comment]
After install 0.3.3 everything is ok. Thank you for so quick response.
