### ISSUE TITLE
Gauge.VisualStudio.Templates should be available for 2017

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-visualstudio#234]
**Actual behavior**
Upon installation, it is currently available only for VS-2015

**Steps to replicate**
* Ensure VS-2017 (Community Edition) is installed
* Install Gauge-VS for 2017 with nightly https://bintray.com/gauge/Gauge.VisualStudio/Nightly/latest.nightly-2018-06-06
* Install https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.gauge-visualstudio-templates. 
> It said the template is already installed for all applicable VS versions
* Try creating a new Gauge-project from the IDE.
> The option is not available on 2017

**Version**
```
Gauge-VS - nightly-2018-06-06
```

**Comment by sriv** [comment]
This issue was moved to getgauge-contrib/gauge-visualstudio-templates#1
