### ISSUE TITLE
Memory issues in VS2017

### ISSUE THREAD

**Issue by Christoffer-Green** [getgauge/gauge-visualstudio#243]
Seems like there might be a memory leak issue with the VS2017 plugin.

### Steps to reproduce
1. Start VS2017 with the gauge-visualstudio plugin
2. Leave the computer on over night, with Visual Studio on
3. Try to continute your work the next day

You get constant 2-3 second lags and the Studio warns about the plugin taking up to much memory.

### Version Information

VisualStudio Version and Edition  :- VS2017 15.6.7
Gauge VisualStudio Plugin Version :- 0.3.6

```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
csharp (0.10.5)
html-report (4.0.6)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
@Christoffer-Green - thanks for raising this, I have started investigating this. 

Just wanted to check if you noticed anything like this with VS2015 and the same version of gauge-visualstudio plugin? 

Also, if you happen to notice this again, could you check your task manager/process monitor to see the resource usage? 

Unfortunately, I can only lay my hands on a Windows VM at the moment, not very ideal for these kind of tests.

**Comment by Christoffer-Green** [comment]
@sriv Sadly never tried the same version of the plugin with VS2015 and don't have any easy way of doing it right now either. But I'll reenable the plugin and see if I can get you some logs and check the resource manager!
