### ISSUE TITLE
GaugePackage Loading Error

### ISSUE THREAD

**Issue by isharasjc** [getgauge/gauge-visualstudio#244]
### Expected behavior
Getting 'The GuagePackage package did not load correctly' error after installing the Gauge for VS Community 2017 (Version 15.9.5).

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. Install Gauge on VS Community 2017 (Version 15.9.5)

### Version Information

VisualStudio Version and Edition  :- Community 2017 (Version 15.9.5)
Gauge VisualStudio Plugin Version :- 0.3.6

C:\Users\dileepa>gauge -v
'gauge' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dileepa>

**Comment by negiDharmendra** [comment]
@isharasjc Looks like Gauge is not installed on your system.  [Gauge visual studio plugin](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1071478.GaugepluginforVisualStudio
) requires [Gauge ](https://github.com/getgauge/gauge)to be installed on the system. Click [here ](https://docs.gauge.org/latest/installation.html#installation
)to see install instructions.
