### ISSUE TITLE
LSP support on visual studio 2019

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-visualstudio#247]

**Comment by negiDharmendra** [comment]
### Language Server Protocol features in visual studios

#### Supported
- initialize
- initialized
- shutdown
- $/cancelRequest
- exit
- textDocument/publishDiagnostics
- textDocument/didOpen
- textDocument/didClose
- textDocument/didSave
- textDocument/codeAction
- textDocument/documentSymbol
- textDocument/definition
- textDocument/completion
- textDocument/formatting
- textDocument/rename
- workspace/symbol
- workspace/didChangeWatchedFiles
- completionItem/resolve ==> completion/resolve

#### Not supported 

- client/registerCapability
- textDocument/codeLens

They have support for [custom message](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019#custom-messages)

**Comment by sriv** [comment]
> - client/registerCapability
> - textDocument/codeLens

The current VS plugin does not make use of the equivalent of codelens. So I suppose that is ok. `registerCapability` might be an issue, need to verify.

Test explorer can remain as is, since LSP does not have support for testing (yet?)

**Comment by nehashri** [comment]
Test explorer is not yet supported, it needs to be added in Visual Studio. 

`registerCapability` is an issue. Without it the a lot of features and integrations will be affected. Currently, we register all capabilities the language runner provides dynamically. Implementing LSP in Visual Studio without it will become tricky.
