### ISSUE TITLE
dotnet core project in visual studio should discover tests and navigate from .spec files to code

### ISSUE THREAD

**Issue by HariharanS** [getgauge/gauge-visualstudio#251]
I am new to Gauge. Previously I was using other BDD tools.
I am using the dotnet template. To start with, I ran the below command to initialize a gauge project.
`gauge init dotnet`

This installs the default dotnet-template.csproj 

### Expected behavior
1. I want to "Test explorer" to lists the tests so that I can run them individually
2. I want to be able to navigate from the .spec file to the code implementation by right clicking and "Go to Definition"
![image](https://user-images.githubusercontent.com/1931027/55400817-9be03f00-559a-11e9-85ff-a01557febb14.png)

### Actual behavior
1. Test explorer window does not discover the tests
2. Cannot navigate from .spec file to code behind

### Steps to reproduce
1. Run gauge init dotnet
2. Open in visual studio
3. Open Test Explorer window to discover tests but none are found
4. Right click on a step in .spec file and choose Go to Definition does not navigate to step implementation

### Version Information

VisualStudio Version and Edition  :-
![image](https://user-images.githubusercontent.com/1931027/55400884-c9c58380-559a-11e9-8811-55e1d17f795c.png)

Gauge VisualStudio Plugin Version :-
![image](https://user-images.githubusercontent.com/1931027/55400932-ebbf0600-559a-11e9-916c-70937ebd5ba3.png)

![image](https://user-images.githubusercontent.com/1931027/55401150-9d5e3700-559b-11e9-810b-2d477acf4b16.png)

**Comment by HariharanS** [comment]
quick additional note - if I use a csharp instead of dotnet template, 
1. when i navigate to test explorer, The tests are listed. 
2. I can run the tests
3. I cannot debug the tests
4. Go to definition on the step in .spec file takes me to the step implementation

![image](https://user-images.githubusercontent.com/1931027/55402691-c41e6c80-559f-11e9-90de-34cad0a0642a.png)

**Comment by zabil** [comment]
Gauge's Visual Studio plugin only supports .net framework at the moment i.e `gauge init csharp`

To get similar (and better) features for .net core, `guage init dotnet`, please use [VS Code](https://code.visualstudio.com/)

**Comment by HariharanS** [comment]
Thanks zabil for your reply.
based on this comment https://github.com/getgauge/gauge-visualstudio/issues/251#issuecomment-478975561
there is still issue with debug tests in Visual studio

**Comment by zabil** [comment]
The screenshot shows breakpoints added to the specification. This does not work.
Have you tried adding breakpoints in the step implementation?
