### ISSUE TITLE
No tests are visible after a successful build.

### ISSUE THREAD

**Issue by ssg47** [getgauge/gauge-visualstudio#254]
### Expected behavior
Tests are visible after a successful build.

### Actual behavior
No tests are visible after a successful build.

### Steps to reproduce
I have attempted to reproduce this and failed.  It happens inconsistently: it hasn't yet happened in 5 attempts to recreate the issue in simple, Gauge-only projects but it has been an issue in a real project.  I realise that I'm not providing you with much to go on at this stage (you can see from #253 (and #206 and #213) my normal approach to recreating).  I will update the ticket if I establish a pattern.  I wondered if anyone else is seeing this.

### Version Information

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Community

Gauge.VisualStudio   1.0   (as reported by Help > About)
Gauge Visual Studio Extension

Gauge plugin for Visual Studio:- 0.3.7
Gauge.VisualStudio.Templates:- 1.1
```
gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
html-report (4.0.8)
json-report (0.3.1)
xml-report (0.2.1)
```

**Comment by ssg47** [comment]
I've just closed my GaugeProject5 (recreation project from #253) and reopened the solution which triggered me reporting this issue and the tests have appeared.

**Comment by nehashri** [comment]
I am not able to reproduce this issue after a successful build. But I am able to reproduce this issue consistently by doing the following.
1. Create a Gauge CSharp project
2. Open the project and build the project from Visual Studio.
3. Run all tests from the Test explorer. This passes.
4. Now edit the example.spec file and add a unimplemeted step to one of the scenarios.
5. Run all tests again. The tests seem to run, but after the run all tests disappear (including the valid scenarios).

If the project is closed an reopened, all the scenarios are shown properly.

### Gauge version:
Gauge version: 1.0.5
Commit Hash: 562f036

**Plugins:**
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
screenshot (0.0.1)

Gauge visual studio extension version : 0.3.7
Visual Studio version : Visual Studio Community 2017 - 15.9.11

**Comment by Debashis9012** [comment]
I have tested this issue with the gauge-visualstudio fix version ```latest.nightly-2019-05-21 ```.
After building project tests are correctly visible.

@ssg47  Could you please try this out by using the latest gauge-visualstudio nightly fix version https://bintray.com/gauge/Gauge.VisualStudio/Nightly and let us know the outcome?
