### ISSUE TITLE
The execution doesn't halt on breakpoints and the test removed from test explorer

### ISSUE THREAD

**Issue by yinzhenzhixin** [getgauge/gauge-visualstudio#258]
### Expected behavior
The execution should halt on marked breakpoints, and the executed tests should not be removed from the play list of the test explorer

### Actual behavior
The execution was stopped with the following error messages, moreover, the test that I try to debug is removed from the play list which means I can't find and select it to run or debug again unless I restart the vs2017
The program '[333036] testhost.exe: Program Trace' has exited with code 0 (0x0).
The program '[333036] testhost.exe' has exited with code 0 (0x0).

### Steps to reproduce
1. Installed the gauge extension for visual studio (2017)
2. Add a csharp gauge project with some specifications
3. Open the test explorer
4. Right click -> Debug Selected Tests on a scenario(s) in the Test explorer. 
5. Check if execution will halt on marked breakpoints.
6. See if the tests are still in the play list of the test explorer

### Version Information

VisualStudio Version and Edition  : Enterprise 2017 15.9.12
Gauge VisualStudio Plugin Version : 0.3.8

```
Run gauge -v on your system and paste the results here.
```
Gauge version: 1.0.6.nightly-2019-05-31
Commit Hash: a2c6f03

Plugins
-------
csharp (0.10.5)
dotnet (0.1.1)
html-report (4.0.8)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by nehashri** [comment]
@yinzhenzhixin The issue you are facing may be similar to https://github.com/getgauge/gauge-visualstudio/issues/254. We will do a release with this fix soon. In the meantime, can you please try installing the nightly version of Visual Studio pluin from https://bintray.com/gauge/Gauge.VisualStudio/Nightly and see if you are still facing issues.

**Comment by yinzhenzhixin** [comment]
@nehashri Thank you. Actually The vs plugin that I installed locally is jsut what you mentioned (gauge.visualstudio-latest.nightly-2019-05-21.vsix). Anyway, I will focus on #254 until the fix works, thanks again

**Comment by Debashis9012** [comment]
Hi @yinzhenzhixin ,

I have tried the above steps to reproduce in a sample project.
For me debug features is working as excepted. I am using `Microsoft Visual Studio Community 2017`
I am using the latest nightly gauge with visual studio plugin. For more details please find the below screenshot.

![vsDebug2sc](https://user-images.githubusercontent.com/46309201/59913054-13549a80-9435-11e9-9414-e5c703f88aa0.JPG)

Could you please provide few information from your side which will be helpful for us to figure out the issue:
1. Are you getting this issue on the sample project?
2. Could you please try this on latest nightly of gauge(gauge nightly: https://bintray.com/gauge/Gauge/Nightly) with visual studio plugin and let us know 
   whether you are still facing the same problem?

**Comment by Apoorva-GA** [comment]
Closing this for now. Feel free to reopen if you are still facing this.
