### ISSUE TITLE
Add support for generating Specs/Scenarios

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#26]
A code generator that puts in templated Scenarios / Steps would help users add these with ease

**Comment by mahendrakariya** [comment]
To add a snippet, we need to create a [custom language service](https://msdn.microsoft.com/en-us/library/bb165744.aspx) in VS.  We have started working on this in [language_service](https://github.com/getgauge/gauge-visualstudio/tree/language_service) branch.

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.

With LSP support for Visual Studio coming up, we might as well use it.
