### ISSUE TITLE
Gauge linked in TFS Builds.

### ISSUE THREAD

**Issue by salmankhwaja** [getgauge/gauge-visualstudio#266]
Hi, 

We are integrating Gauge with TFS Builds. We have successfully ran gauge with OWASP Zap. When we are implementing Gauge with TFS using TFS Build variables, our variables are not being transformed into values from TFS Builds to Gauge environment and ultimately in program. 

Please provide help if you know.

Environment details:

Windows 2012, Command line.
TFS is on Windows Also
Agent is on Windows also.

Gauge is running with windows, python, and OWASP ZAP.

**Comment by Syntax3r** [comment]
I have the same issue..

![Gauge](https://user-images.githubusercontent.com/20611131/73053503-b416a700-3ea9-11ea-84cf-4fa3327302f2.png)

**Comment by zabil** [comment]
> our variables are not being transformed into values from TFS Builds to Gauge environment and ultimately in program.

Can you give an example of how you are trying to access environment variables?

**Comment by Syntax3r** [comment]
I have put the %{variable} in Scenario of Spec file.

Example :
## Open URL with OWASP ZAP

This is a scenario that starts OWASP ZAP
* Start ZAP and Open URL "%{login_page_url}"

Want to replace the "login_page_url" with the variable provide through TFS during build.

**Comment by zabil** [comment]
This is not supported at the moment on specs. You can access the environment variable in the step implementation for example in Java

```
@Step("Start ZAP and Open URL")
public void startZap() {
 String url = System.getenv("login_page_url");
  ...
}
```

@salmankhwaja is this the same issue that you are facing too?

There's a discussion about this here https://github.com/getgauge/gauge/issues/1395

**Comment by salmankhwaja** [comment]
@zabil , 

Thanks. Yeah I was having the same problem.
