### ISSUE TITLE
Executing a group of tests on Visual Studio

### ISSUE THREAD

**Issue by harinee** [getgauge/gauge-visualstudio#46]
Currently when we explore the tests from the Test Explorer window, we can only see a flat structure of tests available.
Can we group these - Spec-wise or tag-wise?
I should be able to run all tests in a spec (or under a tag) at once, as a complete suite in itself.

**Comment by apoorvam** [comment]
This can be done by choosing Group by -> Traits in Test Explorer of Visual Studio.
