### ISSUE TITLE
Gauge features kick off in a non-gauge project

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#65]
Create a regular class library and add a `.spec` or `.md` file. It tries to hightlight it as a Gauge specification and highlights unimplemented step.

**Comment by mahendrakariya** [comment]
We have asked a question for some help on this on MSDN.
https://social.msdn.microsoft.com/Forums/en-US/f9eb751c-89bb-46f8-a2dd-6b5bbfd447d8/disable-vs-package-for-some-projects?forum=visualstudiogeneral
