### ISSUE TITLE
[Test Explorer] filtering test cases using "Traits" is not working properly .

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-visualstudio#69]
<img width="252" alt="screen shot 2015-09-03 at 4 32 17 pm" src="https://cloud.githubusercontent.com/assets/10433272/9656859/6b866656-5259-11e5-9a9f-10814d92ee9e.png">

**Comment by mahendrakariya** [comment]
Filtering happens properly, but display shows them twice. This is because a scenario has two Traits, `Tag` and `Spec`.

**Comment by sriv** [comment]
This is by design, Traits are not exclusive filters, rather they are a way to tag a spec. So, in this case, we have a scenario `Create a new product` that falls under `Specification:Product` and `Tag:login`. Hence it is listed twice.
