### ISSUE TITLE
Data Tables for a spec is not working when gives absolute path along with ':'

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-visualstudio#74]
when using external csv file with complete file path for Data table, it throws below error:

Result StandardOutput:	09:55:43.450 [CRIT] [ParseError] C:\Users\uzma\Documents\Project\gauge-example-csharp-master\specs\customer.spec : line no: 11, Could not resolve table from  table: C:\Users\uzma\Documents\Project\gauge-example-csharp-master\user.csv

Note: same error for special parameters as well.
* say hello to file: C:\Users\uzma\Documents\Project\gauge-example-csharp-master\user.txt
Note : it works when gives: file: user.txt

**Comment by sriv** [comment]
getgauge/gauge/#207 should fix this.

**Comment by sriv** [comment]
Closing this, v0.2.0 of Gauge-VS is released in the gallery.
