### ISSUE TITLE
gets error when select "Analyze code coverage for All Tests"  from test explorer

### ISSUE THREAD

**Issue by uzmar** [getgauge/gauge-visualstudio#76]
click over Run-> Analyze code coverage for All Tests from test explorer

<img width="484" alt="screen shot 2015-09-08 at 2 58 13 pm" src="https://cloud.githubusercontent.com/assets/10433272/9731490/d7394dac-563a-11e5-9194-1e2f519ff69a.png">

**Comment by sriv** [comment]
@uzmar - can you please check if this is resolved in 0.1.0 (https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92)

**Comment by uzmar** [comment]
I retested it with this version. Now it's working fine. Thanks.
