### ISSUE TITLE
Discover Tests not working?

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-visualstudio#82]
Not sure if i'm doing something wrong. But when i install the VS gauge plugin from the gallery i can't see any tests showing up in the test explorer no matter what i do (even if i generate the basic template with "gauge --init csharp")

**Comment by MattFenner** [comment]
not sure what happened here. but uninstalling and reisntalling the plugin seemed to fix this

**Comment by sriv** [comment]
This is weird, indeed. I'll close this for now, feel free to reopen it if you encounter this again.

**Comment by MattFenner** [comment]
it did happen a couple of times. but seems to be working now. if it happens again i will reopen

**Comment by jason-roberts** [comment]
Installing Gauge VS2013 v0.1.0 plugin and then creating a new Gauge project from the VS template creates the project, but after building no tests appear in Test Explorer.

Creating a project from command line, opening in VS, and building also doesn't make tests appear in Test Explorer.

Creating a project from command line, then running the hello_world spec from command line, then opening in VS and building *does* make tests appear in Test Explorer.

**Comment by sriv** [comment]
thanks for the analysis @jason-roberts . I am reopening this issue as a bug. We will investigate this.

**Comment by sriv** [comment]
Thanks to @jason-roberts , and a fresh machine, I could reproduce this. The problem is that the VS Plugins's `TestContainerDiscoverer` does not get the signal at the right event, to scan for Gauge Specs. Working on this now.

**Comment by jason-roberts** [comment]
No worries @sriv :)

**Comment by judeogzewalla** [comment]
I am not able to see the tests either. I tried replicating the steps above, but to no avail. I am running Gauge version: 0.3.1

Plugins
-------
csharp (0.7.1)
html-report (2.0.0)

When I launch VS2013 it looks as though there is a Gauge widow floating on my second monitor, but then it disappears and I cannot see any tests in the VS test explorer.

**Comment by sriv** [comment]
@judeogzewalla - can you please try using v0.2.0 of Gauge-VS plugin? It has a few improvements. 

I shall reopen this issue if you still have problems.

**Comment by konjugen** [comment]
I still have problem. Does not appear on test explorer...
