### ISSUE TITLE
Run tests from a different location

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-visualstudio#83]
I'm guessing there might not be many people needing this. But at my work we have a special case where our application is made up of 100s of dlls.

So the way we work is that once a VS project is built, the dlls are copied to a different directory where our app (and all it's dlls) live. 

So it would be great if there was an option to change the test running to be able to run against the dll that was copied to the new location. rather than defaulting to the one found in the project directory.

This is something that the resharper test runner has, but because of the way gauge works, we can't use this runner.

**Comment by sriv** [comment]
For Gauge to run tests using Binaries from a custom location. Please have a [look here](http://getgauge.io/documentation/user/current/test_code/java/configuration.html#gauge_custom-_build_path).

However, Gauge-VS assumes the build dlls to be available at `bin\<configuration>` directory. Are you looking for a way to tell Gauge VS to use the test binaries from a different location explicitly? Or would you like it if Gauge-VS detects the build output path set in your project and uses it?

**Comment by MattFenner** [comment]
I am wanting a way to get gauge to test against the dll from a different location explictly.

The solution you provided doesn't seem to work as it seems to be an absolute path like you mentioned. is there a way to provide an absolute path.

e.g. my C# project file lives in c:\git\project, whereas i want to make it run the tests from c:\currentbuild\bin. 

also it is worth noting that the page you linked to me is under the java area of the documentation. while it seems to also work for c# so this is probably a bug in the structure of your documentation

**Comment by sriv** [comment]
Sorry about the mixup in the documentation section. `gauge_custom_build_path` is a Gauge Core environment variable, and applies to all languages. We will fix that.

For you case, here is what I tried:

- create a new project `foo`, and run `gauge specs`.
- the output
```
09:42:37.632 [INFO] Build Building Project: C:\Users\srikantv\AppData\Local\Temp\foo\foo.sln
09:42:37.633 [INFO] 
09:42:37.911 [INFO] Build Success
09:42:37.911 [INFO] 
09:42:39.064 [INFO] Executing specification: Specification Heading
09:42:39.069 [INFO] Executing scenario: First scenario
09:42:39.073 [DEBUG] Executing Step: * A context step which gets executed before every scenario
09:42:39.082 [INFO] This is a sample context
09:42:39.087 [DEBUG] Executing Step: * Say "hello" to "gauge"
09:42:39.093 [INFO] hello, gauge!
09:42:39.098 [INFO] Executing scenario: Second scenario for the specification
09:42:39.098 [DEBUG] Executing Step: * A context step which gets executed before every scenario
09:42:39.099 [INFO] This is a sample context
09:42:39.101 [DEBUG] Executing Step: * Say "hello again" to "gauge"
09:42:39.101 [INFO] hello again, gauge!
09:42:39.104 [DEBUG] Executing Step: * Step that takes a table 
     |Product|Description                  |
     |-------|-----------------------------|
     |Gauge  |Test automation with ease    |
     |Mingle |Agile project management     |
     |Snap   |Hosted continuous integration|
     |Gocd   |Continuous delivery platform |
09:42:39.113 [INFO] Product
09:42:39.113 [INFO] DescriptionGauge|Test automation with ease
Mingle|Agile project management
Snap|Hosted continuous integration
Gocd|Continuous delivery platform
09:42:39.323 [DEBUG] Plugin [Html Report] with pid [3092] has exited
09:42:39.423 [INFO] Specifications: 	1 executed, 1 passed, 0 failed, 0 skipped
09:42:39.423 [INFO] Scenarios: 	2 executed, 2 passed, 0 failed, 0 skipped
09:42:39.424 [INFO] Total time taken: 71ms
```

Next:
- build the project separately
- copy the binaries to `c:\some_location`, 
- from the project directory, run `set gauge_custom_build_path="c:\some_location" && gauge specs`. (i.e. set the `gauge_custom_build_path` Environment variable prior to invoking gauge specs). **Please note that I am using absolute path, but relative should work as well**
- the output:
```
09:44:51.239 [INFO] Executing specification: Specification Heading
09:44:51.245 [INFO] Executing scenario: First scenario
09:44:51.248 [DEBUG] Executing Step: * A context step which gets executed before every scenario
09:44:51.257 [INFO] This is a sample context
09:44:51.261 [DEBUG] Executing Step: * Say "hello" to "gauge"
09:44:51.268 [INFO] hello, gauge!
09:44:51.273 [INFO] Executing scenario: Second scenario for the specification
09:44:51.273 [DEBUG] Executing Step: * A context step which gets executed before every scenario
09:44:51.274 [INFO] This is a sample context
09:44:51.277 [DEBUG] Executing Step: * Say "hello again" to "gauge"
09:44:51.277 [INFO] hello again, gauge!
09:44:51.280 [DEBUG] Executing Step: * Step that takes a table 
     |Product|Description                  |
     |-------|-----------------------------|
     |Gauge  |Test automation with ease    |
     |Mingle |Agile project management     |
     |Snap   |Hosted continuous integration|
     |Gocd   |Continuous delivery platform |
09:44:51.289 [INFO] Product
09:44:51.289 [INFO] DescriptionGauge|Test automation with ease
Mingle|Agile project management
Snap|Hosted continuous integration
Gocd|Continuous delivery platform
09:44:51.400 [DEBUG] Plugin [Html Report] with pid [4872] has exited
09:44:51.500 [INFO] Specifications: 	1 executed, 1 passed, 0 failed, 0 skipped
09:44:51.500 [INFO] Scenarios: 	2 executed, 2 passed, 0 failed, 0 skipped
09:44:51.500 [INFO] Total time taken: 72ms
```

Note that Gauge does not build the test project when you specify a location to pick binaries from. 

Now, we do not have a way to override the `gauge_custom_build_path` when invoking the tests via Gauge-VS - so this is still a valid issue.

**Comment by MattFenner** [comment]
ok will try that. I put the variable in the default.properties file which seemed like it was trying to work but didn't handle absolute paths

**Comment by sriv** [comment]
@MattFenner - is this still an issue?
