### ISSUE TITLE
Automatically build before running tests

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-visualstudio#84]
Is there a way to make it so that the gauge visual studio plugin automatically does a build before running the tests (or maybe as a configuration option?) 

I am used to this from the resharper unit test runner and others, and it is actually quite annoying to have to manually build each time before running a test.

the options the resharper unit test runner has are:
- Automatic
- Automatic (Whole Solution)
- Always
- Never

Automatic builds the project only if has changed. Whereas Always make it always do a rebuild i think.

**Comment by sriv** [comment]
This could be tricky. The Gauge VS plugin hooks on to the VS Test explorer, which comes out of the box with VS 2012+. Now Visual Studio Test explorer has a feature that allows you to [Run Tests after every build](https://msdn.microsoft.com/en-us/library/hh270865.aspx#BKMK_Run_tests_after_every_build), but not the other way, i.e. build before running tests.

We do not have a Resharper plugin that can help mirror your NUnit etc. experience. Resharper does have some intelligence under the hood, but it is a closed-source project and there isn't  anything in the VS documentation or general internet about this[^1], unfortunately.

[^1] - Specifically, we need a way to determine the project status (i.e. built, stale, not built) via the VS SDK api (the tricky bit). We also need a clean way to invoke a build of the project that needs building (the easier bit).

**Comment by MattFenner** [comment]
I will check out the option to run tests after every build. might be enough for now (allthough i dont seem to see that option, will look for a bit longer).

Maybe as a version 1 of this feature you could have an option to always build everything before running the tests. If the part about determining the project status is the hard part.

**Comment by sriv** [comment]
> That option looks nice. but it seems to be only available in VS Enterprise :(
That is a bummer indeed. 

>Maybe as a version 1 of this feature you could have an option to always build everything before running the tests. If the part about determining the project status is the hard part.
We contemplated that, but the flip side is that if you have a large solution, you will see a build triggered everytime before each test run.

One compromise option could be - Build project before "Run All Tests", but assume project's built when using "Run Test" individually ?

**Comment by MattFenner** [comment]
Sorry, i don't understand your question.

**Comment by sriv** [comment]
There are two ways to use the test explorer, one is to "Run All Tests", and the other is to select a test and say "Run Test" . My proposal is to build the target project before test run, only when the user intends to "Run All tests".

PS - the formatting of my previous comment was a bit messed up, so I edited it.
