### ISSUE TITLE
" Call was rejected by callee. "

### ISSUE THREAD

**Issue by MattFenner** [getgauge/gauge-visualstudio#85]
I am getting the following error when trying to debug my tests in visual studio:

![image](https://cloud.githubusercontent.com/assets/1695492/11330938/5e1bdcae-91ff-11e5-9db4-6674ad765a3a.png)

generally restarting visual studio has fixed it. but this time it isn't fixing it.

**Comment by MattFenner** [comment]
getting this in a few different projects/solutions now. works fine when running the test but i get this error when i try to debug it

**Comment by MattFenner** [comment]
I also find in task manager that i get a lot of gauge.exe processes getting started and never getting killed. not sure if this is normal (i assume not)

**Comment by MattFenner** [comment]
found this, no idea if it is relevant: 
https://msdn.microsoft.com/en-us/library/ms228772.aspx

**Comment by sriv** [comment]
Thanks for the reference, @MattFenner. The orphaned gauge.exe processes is definitely a big, will investigate that.

**Comment by sriv** [comment]
@MattFenner - gauge v0.3.3 address the orphaned `gauge.exe` processes issue. Ref getgauge/gauge#166 for details. Could you please check and see if this issue still exists? I am closing this for now, please reopen if you notice this behaviour. 

Also, please update to Gauge-VisualStudio v0.2.1.

PS - thanks for the msdn reference.
