### ISSUE TITLE
No tests discovered when there is a parse error

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-visualstudio#93]
If a spec file has a parse error, even though syntax is valid, Visual Studio gives no feedback to the users. 

However, the scenarios in the specs are not listed, since there is a parse error in the file and Gauge API skips specs with parse errors.

Have a way to either

a. highlight parse errors, #12 should fix this
b. In the meantime, log the warnings in the output console.

**Comment by sguptatw** [comment]
Currently the tests are being discovered with parse errors.
@sriv : Can this issue be closed?
