### ISSUE TITLE
New Install of v0.2.0 is missing Project Template

### ISSUE THREAD

**Issue by alexbestul** [getgauge/gauge-visualstudio#96]
I just installed the lastest (v0.2.0) version of the Gauge Visual Studio extension (https://visualstudiogallery.msdn.microsoft.com/dd8ea767-aa75-4771-98f4-6c8a9055ca92), but I can't find the project template referenced in the README file.

Please let me know what I can do to help troubleshoot.

**Comment by sriv** [comment]
Could you please check the [latest build](https://ci.appveyor.com/api/buildjobs/nv22am2s8gqnr89y/artifacts/artifacts/Gauge.VisualStudio.vsix) and see if the Project/Item templates appear? 

What version of Visual Studio are you facing this issue on?

**Comment by alexbestul** [comment]
Still no template.  Additional info that might be useful:

0. I'm testing by going File->New->Project.  I do not have a solution open.
* Here's my VS info:

Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.5.51650

Installed Version: Professional

**Comment by hakito** [comment]
I can also confirm the problem. It works with v0.0.7

Microsoft Visual Studio Premium 2013
Version 12.0.40629.00 Update 5

and

Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1

**Comment by sriv** [comment]
For some weird reason this was working on my local box, but my test VM had the same issue with VS 2015 community.

I have realized that now that this is happening for all vsix artifacts produced via appveyor' s gauges visual studio build. Very strange, will investigate this.

In the meantime, if either of you could get the [nightly build](https://bintray.com/gauge/Gauge.VisualStudio/Nightly/_latestVersion) and see if it is any different?
